---
- name: CHARGEMENT DES VARIABLES PAR DÃ‰FAUT
  include_vars: defaults/main.yml

- name: INSTALLATION DES PAQUETS
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ package_list }}"